apiVersion: v1
kind: Service
metadata:
  name: prescripto-serice
  labels:
    app: prescripto
spec:
  selector:
    app: prescripto
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer