# Generated by Django 6.0.1 on 2026-02-02 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('Blood', 'Blood Tests'), ('Imaging', 'Imaging'), ('Pulmonary', 'Pulmonary Function'), ('Other', 'Other')], default='Blood', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('form', models.CharField(choices=[('Tab', 'Tablet'), ('Cap', 'Capsule'), ('Syp', 'Syrup'), ('Inj', 'Injection'), ('Cream', 'Cream'), ('Lotion', 'Lotion'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Nebulizer', 'Nebulizer'), ('Sachet', 'Sachet')], default='Tab', max_length=20)),
                ('strength', models.CharField(blank=True, help_text='e.g., 500mg, 250ml', max_length=50)),
                ('default_dosage', models.CharField(blank=True, help_text='Common dosage pattern', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'form', 'strength')},
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('clinical_record', models.TextField(blank=True, help_text='Diagnosis and clinical notes')),
                ('dm', models.BooleanField(default=False, verbose_name='DM (Diabetes)')),
                ('htn', models.BooleanField(default=False, verbose_name='HTN (Hypertension)')),
                ('ihd', models.BooleanField(default=False, verbose_name='IHD')),
                ('tb', models.BooleanField(default=False, verbose_name='TB')),
                ('smoking', models.BooleanField(default=False, verbose_name='Smoking')),
                ('is_first_visit', models.BooleanField(default=True)),
                ('pulse', models.CharField(blank=True, max_length=20)),
                ('spo2', models.CharField(blank=True, max_length=20)),
                ('chest_notes', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('follow_up', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinic.patient')),
                ('tests_ordered', models.ManyToManyField(blank=True, to='clinic.labtest')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, help_text='e.g., 500mg', max_length=100)),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
                ('days', models.PositiveIntegerField(default=1, help_text='Number of days')),
                ('instructions', models.CharField(blank=True, help_text='Before/after food, etc.', max_length=200)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='clinic.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
