# Generated by Django 6.0.1 on 2026-02-02 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='custom_medicine',
            field=models.CharField(blank=True, help_text='Type medicine name if not in list', max_length=200),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.medicine'),
        ),
    ]
