# Generated by Django 6.0.1 on 2026-02-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_doctor_prescription_doctor_prescriptiontemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='counseled_in_detail',
            field=models.BooleanField(default=False, verbose_name='Counseled in detail'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instruction_avoid_food',
            field=models.BooleanField(default=False, verbose_name='Avoid Citrus, Fried, Cold and Junk food items'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instruction_gargles',
            field=models.BooleanField(default=False, verbose_name='Gargles after any type of inhaler are mandatory'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instruction_no_smoking',
            field=models.BooleanField(default=False, verbose_name='Smoking, Cold drinks strongly prohibited'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instruction_warm_liquids',
            field=models.BooleanField(default=False, verbose_name='Use warm liquids frequently'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='other_instructions',
            field=models.TextField(blank=True, help_text='Additional custom instructions'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='rescue_rx_given',
            field=models.BooleanField(default=False, verbose_name='Rescue Rx given with IV Steroid and Nebulization'),
        ),
    ]
