# Generated by Django 6.0.1 on 2026-02-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_prescription_counseled_in_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='custom_duration',
            field=models.CharField(blank=True, help_text='Custom duration text', max_length=50),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='duration_choice',
            field=models.CharField(blank=True, choices=[('', 'Select Duration'), ('1week', '1 Week'), ('2weeks', '2 Weeks'), ('1month', '1 Month'), ('2months', '2 Months'), ('custom', 'Custom')], default='', max_length=20),
        ),
    ]
