# Generated by Django 6.0.1 on 2026-02-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_prescriptionmedicine_custom_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='hep_b',
            field=models.BooleanField(default=False, verbose_name='Hep-B'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='hep_c',
            field=models.BooleanField(default=False, verbose_name='Hep-C'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='obesity',
            field=models.BooleanField(default=False, verbose_name='Obesity'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='other_history',
            field=models.CharField(blank=True, help_text='Other medical history notes', max_length=200),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='afternoon',
            field=models.PositiveIntegerField(default=0, help_text='Number of tablets in afternoon'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='evening',
            field=models.PositiveIntegerField(default=0, help_text='Number of tablets in evening'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='morning',
            field=models.PositiveIntegerField(default=0, help_text='Number of tablets in morning'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='night',
            field=models.PositiveIntegerField(default=0, help_text='Number of tablets at night'),
        ),
    ]
