# Generated by Django 6.0.1 on 2026-02-04 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_prescription_hep_b_prescription_hep_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
