# Generated by Django 6.0.1 on 2026-02-05 12:11

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_add_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=clinic.models.get_current_local_date),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='time',
            field=models.TimeField(blank=True, default=clinic.models.get_current_local_time, null=True),
        ),
    ]
