# Generated by Django 6.0.1 on 2026-02-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_prescription_date_alter_prescription_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g., 120/80', max_length=30),
        ),
        migrations.AddField(
            model_name='prescription',
            name='other_vitals',
            field=models.TextField(blank=True, help_text='Any additional vital notes'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='respiratory_rate',
            field=models.CharField(blank=True, help_text='e.g., 18/min', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='sugar',
            field=models.CharField(blank=True, help_text='e.g., 140 mg/dL', max_length=30),
        ),
        migrations.AddField(
            model_name='prescription',
            name='temperature',
            field=models.CharField(blank=True, help_text='e.g., 98.6 F', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='form',
            field=models.CharField(choices=[('Tab', 'Tablet'), ('Dispersible Tablet', 'Dispersible Tablet'), ('Cap', 'Capsule'), ('Syp', 'Syrup'), ('Inj', 'Injection'), ('Nasal Spray', 'Nasal Spray'), ('Cream', 'Cream'), ('Gel', 'Gel'), ('Ointment', 'Ointment'), ('Lotion', 'Lotion'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Nebulizer', 'Nebulizer'), ('Nebulizer Solution', 'Nebulizer Solution'), ('Sachet', 'Sachet')], default='Tab', max_length=20),
        ),
    ]
