# Generated by Django 4.2.28 on 2026-02-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_prescription_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemedicine',
            name='custom_duration',
            field=models.CharField(blank=True, help_text='Custom duration text', max_length=50),
        ),
    ]
