# Generated by Django 4.2.28 on 2026-02-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_templatemedicine_custom_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, help_text='Primary diagnosis/title', max_length=200),
        ),
    ]
