# Generated by Django 4.2.28 on 2026-02-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_prescription_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, help_text="Diagnosis details shown after 'Clinical Record:' heading"),
        ),
    ]
