# Generated by Django 4.2.28 on 2026-02-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_alter_prescription_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='refer_to',
            field=models.CharField(blank=True, help_text='Referred specialty/department', max_length=120),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
