# Generated by Django 4.2.30 on 2026-07-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_prescription_refer_to_alter_prescription_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='refer_to',
        ),
    ]
