# Generated by Django 4.2.30 on 2026-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_remove_prescription_refer_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Admission Date'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='bed_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bed Number'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diet_instructions',
            field=models.TextField(blank=True, help_text='e.g., Soft diet, NPO, Clear liquids only...', verbose_name='Diet Instructions'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='injections',
            field=models.TextField(blank=True, help_text='e.g., Inj. Ceftriaxone 1g IV BD, Inj. Hydrocortisone 200mg IV stat...', verbose_name='Injections / IV Medications'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_admitted',
            field=models.BooleanField(default=False, verbose_name='Admitted Patient (IPD)'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='iv_fluids',
            field=models.TextField(blank=True, help_text='e.g., NS 1000ml over 8hrs, D5W 500ml...', verbose_name='IV Fluids & Drips'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='monitoring',
            field=models.TextField(blank=True, help_text='e.g., Vitals 4 hourly, I/O charting, SpO2 monitoring...', verbose_name='Monitoring / Nursing Orders'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='nebulization',
            field=models.TextField(blank=True, help_text='e.g., Nebulize with Salbutamol + Ipratropium 6 hourly...', verbose_name='Nebulization Orders'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='other_orders',
            field=models.TextField(blank=True, help_text='Any additional IPD treatment orders', verbose_name='Other Treatment Orders'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='ward',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ward'),
        ),
    ]
