# Generated by Django 4.2.30 on 2026-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_prescription_admission_date_prescription_bed_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='diet_instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='injections',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='iv_fluids',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='monitoring',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='nebulization',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='other_orders',
        ),
        migrations.AddField(
            model_name='prescription',
            name='ipd_prescription',
            field=models.TextField(blank=True, help_text='Type IPD prescription or orders here', verbose_name='IPD Prescription / Orders'),
        ),
    ]
