# Generated by Django 4.2.30 on 2026-10-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_prescription_pregnancy_and_weight_reduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='afternoon',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Number of tablets/dose in afternoon', max_digits=3),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='evening',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Number of tablets/dose in evening', max_digits=3),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='morning',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Number of tablets/dose in morning', max_digits=3),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='night',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Number of tablets/dose at night', max_digits=3),
        ),
    ]
