# Generated by Django 4.2.30 on 2026-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_alter_prescriptionmedicine_afternoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='influvac_vaccine',
            field=models.BooleanField(default=False, verbose_name='2026/2027 Influvac /vaxigrip ...I/M once only'),
        ),
    ]
