# Generated by Django 4.2.30 on 2026-10-09 16:11

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_prescription_influvac_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(blank=True, default=clinic.models.get_current_local_date, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='days',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Number of days', null=True),
        ),
    ]
